version: "3.4"

services:
  express2021:
    image: express2021
    build: .
    volumes:
      - ./src:/usr/src/app/src
      # context: .
      # dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 9229:9229 ##
    command: sh -c "npm install  && npm run debug" ##
